steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg=VITE_WAQI_TOKEN=$_VITE_WAQI_TOKEN'
      - '-t'
      - 'gcr.io/noida-city-dir/noida-city-dir:latest'
      - '.'
images:
  - 'gcr.io/noida-city-dir/noida-city-dir:latest'
substitutions:
  _VITE_WAQI_TOKEN: ''
